'use client'

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TCzkJhMSzVa
 */
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { useEffect, useState } from "react";

export function SQLEditor() {
  const [panelWidth, setPanelWidth] = useState(50);
  const [isDragging, setIsDragging] = useState(false);

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      let nextWidth = e.clientX / window.innerWidth * 100;
      nextWidth = Math.min(Math.max(nextWidth, 20), 80);
      setPanelWidth(nextWidth);
    }

    const handleMouseUp = () => {
      setIsDragging(false);
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);
    }

    const handleMouseDown = () => {
      setIsDragging(true);
      document.addEventListener('mousemove', handleMouseMove);
      document.addEventListener('mouseup', handleMouseUp);
    }

    const resizerElement = document.querySelector('.cursor-ew-resize');
    if (resizerElement) {
      resizerElement.addEventListener('mousedown', handleMouseDown);
    }

    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);

      if (resizerElement) {
        resizerElement.removeEventListener('mousedown', handleMouseDown);
      }
    }
  }, []);
  
  return (
    <div className="flex h-screen bg-[#008080]">
      <div
        style={{ width: `${panelWidth}%` }}
        className={`flex flex-col bg-[#C0C0C0] overflow-hidden border-4 border-[#008080] ${isDragging ? "select-none" : ''}`}
      >
        <div className="px-4 py-2 flex items-center bg-[#808080] h-14">
          <h2 className="text-lg font-semibold text-[#000080]">SQL Editor</h2>
          <Button className="ml-auto px-4 bg-[#000080] text-[#FFFFFF] border-2 border-[#C0C0C0]" variant="outline">
            Run
          </Button>
        </div>
        <Textarea className={`flex-1 resize-none rounded-none border-none p-4 text-black bg-[#FFFFFF] ${isDragging && "select-none"}`} placeholder="SELECT * FROM Users WHERE Age > 30" />
      </div>
      <div className="w-px h-full bg-yellow-500 mx-auto cursor-ew-resize p-1" />
      <div className={`flex flex-col grow bg-[#C0C0C0] overflow-hidden border-4 border-[#008080] ${isDragging ? "select-none" : ''}`}>
        <div className="px-4 py-2 flex items-center bg-[#808080] h-14">
          <h2 className="text-lg font-semibold text-[#000080]">Results</h2>
        </div>
        <div className="flex-1 overflow-auto p-4 bg-[#FFFFFF]">
          <p className="text-sm text-[#000080]">Results: 45 records found</p>
          <p className="text-sm text-[#000080]">1. John, 35</p>
          <p className="text-sm text-[#000080]">2. Jane, 33</p>
        </div>
      </div>
    </div>
  )
}
